In [1]:
from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np
import os
import time
plt.rcParams['figure.figsize'] = [16, 8]

In [38]:
# generate a random integer matrix
A = np.random.randint(5, size=(1000, 4))

In [39]:
%%time
U, S, VT = np.linalg.svd(A)
U.round(3), S.round(3), VT.round(3)

Wall time: 70.8 ms


(array([[-0.041, -0.014,  0.003, ..., -0.024,  0.002, -0.001],
        [-0.037,  0.009,  0.014, ..., -0.028, -0.051, -0.003],
        [-0.026,  0.04 , -0.035, ..., -0.021,  0.013,  0.078],
        ...,
        [-0.022,  0.029,  0.03 , ...,  0.997, -0.002,  0.001],
        [-0.019,  0.057, -0.001, ..., -0.002,  0.996, -0.001],
        [-0.018,  0.02 , -0.011, ...,  0.001, -0.001,  0.994]]),
 array([134.221,  45.114,  44.122,  43.46 ]),
 array([[-0.491, -0.506, -0.492, -0.511],
        [-0.466,  0.624,  0.358, -0.515],
        [ 0.722, -0.058,  0.054, -0.687],
        [ 0.143,  0.592, -0.792,  0.039]]))

In [40]:
%%time
S, V = np.linalg.eig(A.T@A)
# Sigma contains square roots of eigenvalues of matrix A.T*A
S = np.sqrt(S)
VT = V.T
U = A @ V @ np.linalg.inv(np.diag(S))
U.round(3), S.round(3), VT.round(3)

Wall time: 2.99 ms


(array([[ 0.041,  0.014,  0.003, -0.015],
        [ 0.037, -0.009,  0.014,  0.048],
        [ 0.026, -0.04 , -0.035,  0.038],
        ...,
        [ 0.022, -0.029,  0.03 ,  0.029],
        [ 0.019, -0.057, -0.001,  0.004],
        [ 0.018, -0.02 , -0.011, -0.072]]),
 array([134.221,  45.114,  44.122,  43.46 ]),
 array([[ 0.491,  0.506,  0.492,  0.511],
        [ 0.466, -0.624, -0.358,  0.515],
        [ 0.722, -0.058,  0.054, -0.687],
        [ 0.143,  0.592, -0.792,  0.039]]))

In [42]:
def snapshot(X):
    S, V = np.linalg.eig(X.T@X)
    # Sigma contains square roots of eigenvalues of matrix A.T*A
    S = np.sqrt(S)
    VT = V.T
    U = X @ V @ np.linalg.inv(np.diag(S))
    return U, S, VT
snapshot(A)

(array([[ 0.04092496,  0.01376534,  0.00340346, -0.01489464],
        [ 0.03732811, -0.00945846,  0.0139318 ,  0.04792358],
        [ 0.02636443, -0.0404729 , -0.0351677 ,  0.0380623 ],
        ...,
        [ 0.02228424, -0.02876839,  0.03002606,  0.02923507],
        [ 0.01863917, -0.05737385, -0.00149062,  0.00443681],
        [ 0.01846566, -0.02031155, -0.0107112 , -0.07200973]]),
 array([134.22063139,  45.11418924,  44.12186721,  43.46024473]),
 array([[ 0.49051723,  0.50606001,  0.49179054,  0.51131026],
        [ 0.46639706, -0.62431281, -0.35771822,  0.51453375],
        [ 0.72212065, -0.05770065,  0.05366654, -0.68726436],
        [ 0.14285796,  0.59228998, -0.79202251,  0.03852966]]))