In [3]:
import numpy as np

1. Generate an n by m matrix, with a prescribed column rank, r, that is less than m. For example,
	generate a 10 by 5 matrix with column rank 3.

In [4]:
n, m, r = 10, 5, 3
#generate
A = np.random.randint(0,3, size=(n,r))
print(A)
for i in range(r,m):
    k = np.random.rand()
    rdm_col = np.random.randint(r)
    new_col = k*A[:,rdm_col].reshape(-1,1)
    #print(new_col.shape)
    A = np.hstack((A, new_col))
print(A)
np.linalg.matrix_rank(A)

[[2 1 2]
 [1 2 1]
 [2 2 2]
 [0 0 0]
 [1 2 0]
 [1 0 0]
 [1 1 2]
 [2 0 2]
 [2 1 1]
 [1 1 2]]
(10, 1)
(10, 1)
[[2.         1.         2.         1.95816766 0.05267908]
 [1.         2.         1.         0.97908383 0.02633954]
 [2.         2.         2.         1.95816766 0.05267908]
 [0.         0.         0.         0.         0.        ]
 [1.         2.         0.         0.97908383 0.02633954]
 [1.         0.         0.         0.97908383 0.02633954]
 [1.         1.         2.         0.97908383 0.02633954]
 [2.         0.         2.         1.95816766 0.05267908]
 [2.         1.         1.         1.95816766 0.05267908]
 [1.         1.         2.         0.97908383 0.02633954]]


3

2. Use a random projection onto a n by r matrix and a n by r + 1 matrix. You can use either a Gaussian
	projection or a random matrix with +1 and -1 entries chosen independently.

In [16]:
# Gaussian distribution
np.random.normal(0, 1, size=(r,r))

array([[-0.03196649, -2.01459975, -0.85031436],
       [-2.67329047,  0.15025581, -0.18170791],
       [-0.29722179,  0.75608293,  0.40071303]])

In [ ]:
def rSVD(X,r,q,p):
    # Step 1: Sample column space of X with P matrix
    ny = X.shape[1]
    # Gaussian with mean  =  0, sigma = 1
    P = np.random.normal(0,1,(ny,r+p))

    Z = X @ P
    print('Rank(Z)',np.linalg.matrix_rank(Z))
    for k in range(q):
        Z = X @ (X.T @ Z)

    Q, R = np.linalg.qr(Z,mode='reduced')

    # Step 2: Compute SVD on projected Y = Q.T @ X
    Y = Q.T @ X
    UY, S, VT = np.linalg.svd(Y,full_matrices=0)
    U = Q @ UY
    print('Rank(Y)',np.linalg.matrix_rank(Y))
    return U, S, VT

q = 1   # Power iterations
p = 5   # Oversampling parameter

rU, rS, rVT = rSVD(A,r,q,p)
np.linalg.matrix_rank(rU)

In [18]:
np.random.randint(0,2, size=(n,r))

array([[0, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0]])

3. Compute the rank of the projection.